---

- name: Copier les fichiers de configuration NGINX
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: 'nginx.conf.j2', dest: './lib/{{env}}/nginx/nginx.conf' }
#    - { src: 'site.conf.j2', dest: './lib/{{env}}/nginx/sites-available/site.conf' }
#  notify: restart nginx container


